site_name: WimsAPI Documentation
site_author: Quentin Coumes
repo_url: https://github.com/qcoumes/wimsapi

nav:
  - Installation: index.md
  - API:
    - Class: class.md
    - User: user.md
    - Sheet: sheet.md
    - Exercise: exercise.md
    - Exam: exam.md
    - Exceptions: exceptions.md
  - "Low-Level API": api.md
  - "Change log": CHANGES.md
  - License: license.md
  - Github: https://github.com/qcoumes/wimsapi

theme: readthedocs
